import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { extname, join, relative, resolve } from "node:path";

import * as p from "@clack/prompts";

export async function runBuild(cwd: string = process.cwd()): Promise<void> {
  p.intro("SimAPI — build");

  const configPath = resolve(cwd, "simapi.config.ts");
  if (!existsSync(configPath)) {
    p.cancel("simapi.config.ts not found. Are you in a SimAPI project?");
    process.exit(1);
  }

  const distDir = resolve(cwd, ".simapi", "dist");
  const tmpDir = resolve(cwd, ".simapi", "_build");
  const endpointsDir = resolve(cwd, "endpoints");
  const authHandlerPath = resolve(cwd, "authHandler.ts");

  const s = p.spinner();
  s.start("Compiling project");

  try {
    // Discover endpoint files
    const endpointFiles = existsSync(endpointsDir)
      ? await scanTsFiles(endpointsDir)
      : [];

    const hasAuth = existsSync(authHandlerPath);

    // Build static imports for the production entry
    const importLines: string[] = [];
    const endpointVars: string[] = [];

    let i = 0;
    for (const file of endpointFiles) {
      const relPath = relative(tmpDir, file).replace(/\\/g, "/");
      const varName = `mod${i}`;
      importLines.push(`import * as ${varName} from "${relPath}";`);
      endpointVars.push(varName);
      i++;
    }

    const configRel = relative(tmpDir, configPath).replace(/\\/g, "/");
    const authRel = hasAuth
      ? relative(tmpDir, authHandlerPath).replace(/\\/g, "/")
      : null;

    const entry = buildProductionEntry({
      configRel,
      authRel,
      importLines,
      endpointVars,
    });

    // Write temp entry
    await mkdir(tmpDir, { recursive: true });
    const entryPath = join(tmpDir, "server.ts");
    await writeFile(entryPath, entry);

    // Use tsdown programmatic API to bundle
    const { build } = await import("tsdown");
    await build({
      entry: { server: entryPath },
      outDir: distDir,
      format: ["esm"],
      dts: false,
      clean: true,
      sourcemap: false,
      // Keep runtime deps external; bundle everything else (user code + simapi core)
      external: ["hono", "@hono/node-server", "tsx"],
    });

    s.stop("Build complete");
    p.outro(`Output: .simapi/dist/server.mjs\nRun with: npm run start`);
  } catch (err) {
    s.stop("Build failed");
    console.error(err);
    process.exit(1);
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}

async function scanTsFiles(dir: string): Promise<string[]> {
  const files: string[] = [];
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        files.push(...(await scanTsFiles(full)));
      } else if ([".ts", ".js"].includes(extname(entry.name))) {
        files.push(full);
      }
    }
  } catch {
    // ignore missing directories
  }
  return files;
}

function buildProductionEntry(opts: {
  configRel: string;
  authRel: string | null;
  importLines: string[];
  endpointVars: string[];
}): string {
  const { configRel, authRel, importLines, endpointVars } = opts;

  const authImport = authRel ? `import { authHandler } from "${authRel}";` : "";

  const endpointCollection =
    endpointVars.length > 0
      ? `const allMods = [${endpointVars.join(", ")}];\n` +
        `const endpoints = allMods.flatMap((m) => Object.values(m)).filter(isEndpoint);`
      : `const endpoints: EndpointDefinition[] = [];`;

  return `// Auto-generated by simapi build — do not edit
import { Hono } from "hono";
import { serve } from "@hono/node-server";
import { AppRequest, AppResponse, ValidationError } from "simapi";
import type { EndpointDefinition } from "simapi";
import config from "${configRel}";
${authImport}
${importLines.join("\n")}

function isEndpoint(v: unknown): v is EndpointDefinition {
  if (typeof v !== "object" || v === null) return false;
  const r = v as Record<string, unknown>;
  return typeof r.path === "string" && typeof r.method === "string" &&
    typeof r.type === "string" && typeof r.handler === "function";
}

${endpointCollection}

const app = new Hono();

app.onError((err, c) => {
  if (err instanceof ValidationError) {
    return err.format === "laravel"
      ? c.json({ message: "The given data was invalid.", errors: err.errorBag }, 422)
      : c.json({ issues: Object.entries(err.errorBag).flatMap(([f, ms]) => ms.map((m) => ({ path: [f], message: m }))) }, 422);
  }
  console.error("[SimAPI]", err);
  return c.json({ message: "Internal server error" }, 500);
});

for (const endpoint of endpoints) {
  app.on(endpoint.method, endpoint.path, async (c) => {
    const headers: Record<string, string> = {};
    c.req.raw.headers.forEach((v, k) => { headers[k] = v; });

    let body: Record<string, unknown> = {};
    const ct = c.req.header("content-type") ?? "";
    if (ct.includes("application/json"))
      body = await c.req.json<Record<string, unknown>>().catch(() => ({}));
    else if (ct.includes("application/x-www-form-urlencoded")) {
      const form = await c.req.formData().catch(() => null);
      form?.forEach((v, k) => { body[k] = v; });
    }

    const query: Record<string, string> = {};
    new URL(c.req.url).searchParams.forEach((v, k) => { query[k] = v; });

    const req = new AppRequest(headers, body, query, c.req.param() as Record<string, string>);

    if (endpoint.type === "secure") {
      ${authRel ? "const ar = config.authHandler ? config.authHandler(req) : (authHandler(req));" : "const ar = config.authHandler?.(req);"}
      if (ar instanceof AppResponse) return c.json(ar.body, ar.status as never);
    }

    const res = await endpoint.handler(req);
    return c.json(res.body, res.status as never);
  });
}

const port = Number(process.env.PORT ?? config.port ?? 3000);
serve({ fetch: app.fetch, port }, (info) => {
  console.log(\`\\n  SimAPI running at http://localhost:\${info.port}\\n\`);
});
`;
}
